En este notebook se realiza el preprocesamiento de las opiniones de los clientes con el objetivo de preparar los textos para las fases posteriores de análisis y modelado.

Se aplicarán diferentes técnicas de limpieza para reducir el ruido presente en las reviews y facilitar que los algoritmos de Machine Learning puedan extraer información relevante.

In [1]:
import pandas as pd
import re
import nltk

In [2]:
from google.colab import files

uploaded = files.upload()

Saving amazon_reviews_eda.csv to amazon_reviews_eda.csv

In [3]:
df = pd.read_csv("amazon_reviews_eda.csv")

df.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,review,review_length
0,3.0,Smells like gasoline! Going back!,First & most offensive: they reek of gasoline ...,[{'small_image_url': 'https://m.media-amazon.c...,B083NRGZMM,B083NRGZMM,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1658185117948,0,True,Smells like gasoline! Going back! First & most...,1467
1,1.0,Didn’t work at all lenses loose/broken.,These didn’t work. Idk if they were damaged in...,[],B07N69T6TM,B07N69T6TM,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1592678549731,0,True,Didn’t work at all lenses loose/broken. These ...,265
2,5.0,Excellent!,I love these. They even come with a carry case...,[],B01G8JO5F2,B01G8JO5F2,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1523093017534,0,True,Excellent! I love these. They even come with a...,480
3,5.0,Great laptop backpack!,I was searching for a sturdy backpack for scho...,[],B001OC5JKY,B001OC5JKY,AGGZ357AO26RQZVRLGU4D4N52DZQ,1290278495000,18,True,Great laptop backpack! I was searching for a s...,1112
4,5.0,Best Headphones in the Fifties price range!,I've bought these headphones three times becau...,[],B013J7WUGC,B07CJYMRWM,AG2L7H23R5LLKDKLBEF2Q3L2MVDA,1676601581238,0,True,Best Headphones in the Fifties price range! I'...,284

In [4]:
df.info()
print(df.loc[0, "review"])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rating             50000 non-null  float64
 1   title              49995 non-null  object
 2   text               49998 non-null  object
 3   images             50000 non-null  object
 4   asin               50000 non-null  object
 5   parent_asin        50000 non-null  object
 6   user_id            50000 non-null  object
 7   timestamp          50000 non-null  int64
 8   helpful_vote       50000 non-null  int64
 9   verified_purchase  50000 non-null  bool
 10  review             50000 non-null  object
 11  review_length      50000 non-null  int64
dtypes: bool(1), float64(1), int64(3), object(7)
memory usage: 4.2+ MB
Smells like gasoline! Going back! First & most offensive: they reek of gasoline so if you are sensitive/allergic to petroleum products like I am you will want to pass on these.  Second: the phone adapter is useless as-is. Mine was not drilled far enough to be able to tighten it into place for my iPhone 12 max. It just slipped & slid all over. Stupid me putting the adapter together first without picking up the binoculars to smell them bc I wasted 15 minutes trying to figure out how to put the adapter together bc it does not come with instructions!  I had to come back here to the website which was a total pain. Third: the tripod is also useless. I would not trust the iOS to hold my $1600 phone nor even a Mattel Barbie for that matter. It’s just inefficient for the job imo.  Third: in order to try to give an honest review I did don gloves & eyewear to check the binoculars out.  They seemed average except for mine seemed to be missing about 10% of the film costing in the lower edge of one of the lenses which would have ruined every video & photograph unplanned to take so for me these are a very huge hard pass.  I expect the accessories that come with the main product to be as good or better than the product I’m buying. Otherwise I would just buy the product as a stand alone.  Sadly, I found a decent pair of binoculars last year with a much better quality phone adapter & tripod, but they had a defect too.  Guess I’m going to have to pay more.  Ugh.

In [5]:
#limpieza básica
def limpiar_texto_basico(texto):
    texto = texto.lower()
    texto = texto.replace("\n", " ")
    texto = texto.replace("\r", " ")
    texto = re.sub(r"\s+", " ", texto)
    texto = texto.strip()
    return texto

In [6]:
df["review_clean_basic"] = df["review"].apply(limpiar_texto_basico)

df[["review", "review_clean_basic"]].head()

,review,review_clean_basic
0,Smells like gasoline! Going back! First & most...,smells like gasoline! going back! first & most...
1,Didn’t work at all lenses loose/broken. These ...,didn’t work at all lenses loose/broken. these ...
2,Excellent! I love these. They even come with a...,excellent! i love these. they even come with a...
3,Great laptop backpack! I was searching for a s...,great laptop backpack! i was searching for a s...
4,Best Headphones in the Fifties price range! I'...,best headphones in the fifties price range! i'...

In [7]:
#comparar visualización del texto original con la limpieza
print("REVIEW ORIGINAL:")
print(df.loc[0, "review"])

print("\nREVIEW LIMPIA:")
print(df.loc[0, "review_clean_basic"])

REVIEW ORIGINAL:
Smells like gasoline! Going back! First & most offensive: they reek of gasoline so if you are sensitive/allergic to petroleum products like I am you will want to pass on these.  Second: the phone adapter is useless as-is. Mine was not drilled far enough to be able to tighten it into place for my iPhone 12 max. It just slipped & slid all over. Stupid me putting the adapter together first without picking up the binoculars to smell them bc I wasted 15 minutes trying to figure out how to put the adapter together bc it does not come with instructions!  I had to come back here to the website which was a total pain. Third: the tripod is also useless. I would not trust the iOS to hold my $1600 phone nor even a Mattel Barbie for that matter. It’s just inefficient for the job imo.  Third: in order to try to give an honest review I did don gloves & eyewear to check the binoculars out.  They seemed average except for mine seemed to be missing about 10% of the film costing in the lower edge of one of the lenses which would have ruined every video & photograph unplanned to take so for me these are a very huge hard pass.  I expect the accessories that come with the main product to be as good or better than the product I’m buying. Otherwise I would just buy the product as a stand alone.  Sadly, I found a decent pair of binoculars last year with a much better quality phone adapter & tripod, but they had a defect too.  Guess I’m going to have to pay more.  Ugh.

REVIEW LIMPIA:
smells like gasoline! going back! first & most offensive: they reek of gasoline so if you are sensitive/allergic to petroleum products like i am you will want to pass on these. second: the phone adapter is useless as-is. mine was not drilled far enough to be able to tighten it into place for my iphone 12 max. it just slipped & slid all over. stupid me putting the adapter together first without picking up the binoculars to smell them bc i wasted 15 minutes trying to figure out how to put the adapter together bc it does not come with instructions! i had to come back here to the website which was a total pain. third: the tripod is also useless. i would not trust the ios to hold my $1600 phone nor even a mattel barbie for that matter. it’s just inefficient for the job imo. third: in order to try to give an honest review i did don gloves & eyewear to check the binoculars out. they seemed average except for mine seemed to be missing about 10% of the film costing in the lower edge of one of the lenses which would have ruined every video & photograph unplanned to take so for me these are a very huge hard pass. i expect the accessories that come with the main product to be as good or better than the product i’m buying. otherwise i would just buy the product as a stand alone. sadly, i found a decent pair of binoculars last year with a much better quality phone adapter & tripod, but they had a defect too. guess i’m going to have to pay more. ugh.

In [8]:
#eliminar signos de puntuación
def eliminar_puntuacion(texto):
    texto = re.sub(r"[^\w\s]", "", texto)
    return texto

In [9]:
df["review_no_punctuation"] = df["review_clean_basic"].apply(eliminar_puntuacion)

In [10]:
print("ANTES")
print(df.loc[0, "review_clean_basic"])

print("\nDESPUÉS")
print(df.loc[0, "review_no_punctuation"])

ANTES
smells like gasoline! going back! first & most offensive: they reek of gasoline so if you are sensitive/allergic to petroleum products like i am you will want to pass on these. second: the phone adapter is useless as-is. mine was not drilled far enough to be able to tighten it into place for my iphone 12 max. it just slipped & slid all over. stupid me putting the adapter together first without picking up the binoculars to smell them bc i wasted 15 minutes trying to figure out how to put the adapter together bc it does not come with instructions! i had to come back here to the website which was a total pain. third: the tripod is also useless. i would not trust the ios to hold my $1600 phone nor even a mattel barbie for that matter. it’s just inefficient for the job imo. third: in order to try to give an honest review i did don gloves & eyewear to check the binoculars out. they seemed average except for mine seemed to be missing about 10% of the film costing in the lower edge of one of the lenses which would have ruined every video & photograph unplanned to take so for me these are a very huge hard pass. i expect the accessories that come with the main product to be as good or better than the product i’m buying. otherwise i would just buy the product as a stand alone. sadly, i found a decent pair of binoculars last year with a much better quality phone adapter & tripod, but they had a defect too. guess i’m going to have to pay more. ugh.

DESPUÉS
smells like gasoline going back first  most offensive they reek of gasoline so if you are sensitiveallergic to petroleum products like i am you will want to pass on these second the phone adapter is useless asis mine was not drilled far enough to be able to tighten it into place for my iphone 12 max it just slipped  slid all over stupid me putting the adapter together first without picking up the binoculars to smell them bc i wasted 15 minutes trying to figure out how to put the adapter together bc it does not come with instructions i had to come back here to the website which was a total pain third the tripod is also useless i would not trust the ios to hold my 1600 phone nor even a mattel barbie for that matter its just inefficient for the job imo third in order to try to give an honest review i did don gloves  eyewear to check the binoculars out they seemed average except for mine seemed to be missing about 10 of the film costing in the lower edge of one of the lenses which would have ruined every video  photograph unplanned to take so for me these are a very huge hard pass i expect the accessories that come with the main product to be as good or better than the product im buying otherwise i would just buy the product as a stand alone sadly i found a decent pair of binoculars last year with a much better quality phone adapter  tripod but they had a defect too guess im going to have to pay more ugh

In [11]:
#eliminar numeros
def eliminar_numeros(texto):
    texto = re.sub(r"\d+", "", texto)
    return texto

df["review_no_numbers"] = df["review_no_punctuation"].apply(eliminar_numeros)

#aplicar stopwords

In [12]:
#stopwords
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [13]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))

In [14]:
#crear función para eliminarlas
def eliminar_stopwords(texto):
    palabras = texto.split()
    palabras_limpias = []

    for palabra in palabras:
        if palabra not in stop_words:
            palabras_limpias.append(palabra)

    texto_limpio = " ".join(palabras_limpias)
    return texto_limpio

In [15]:
#aplicar función
df["review_no_stopwords"] = df["review_no_numbers"].apply(eliminar_stopwords)

In [16]:
print("ANTES")
print(df.loc[0, "review_no_numbers"])

print("\nDESPUÉS")
print(df.loc[0, "review_no_stopwords"])

ANTES
smells like gasoline going back first  most offensive they reek of gasoline so if you are sensitiveallergic to petroleum products like i am you will want to pass on these second the phone adapter is useless asis mine was not drilled far enough to be able to tighten it into place for my iphone  max it just slipped  slid all over stupid me putting the adapter together first without picking up the binoculars to smell them bc i wasted  minutes trying to figure out how to put the adapter together bc it does not come with instructions i had to come back here to the website which was a total pain third the tripod is also useless i would not trust the ios to hold my  phone nor even a mattel barbie for that matter its just inefficient for the job imo third in order to try to give an honest review i did don gloves  eyewear to check the binoculars out they seemed average except for mine seemed to be missing about  of the film costing in the lower edge of one of the lenses which would have ruined every video  photograph unplanned to take so for me these are a very huge hard pass i expect the accessories that come with the main product to be as good or better than the product im buying otherwise i would just buy the product as a stand alone sadly i found a decent pair of binoculars last year with a much better quality phone adapter  tripod but they had a defect too guess im going to have to pay more ugh

DESPUÉS
smells like gasoline going back first offensive reek gasoline sensitiveallergic petroleum products like want pass second phone adapter useless asis mine drilled far enough able tighten place iphone max slipped slid stupid putting adapter together first without picking binoculars smell bc wasted minutes trying figure put adapter together bc come instructions come back website total pain third tripod also useless would trust ios hold phone even mattel barbie matter inefficient job imo third order try give honest review gloves eyewear check binoculars seemed average except mine seemed missing film costing lower edge one lenses would ruined every video photograph unplanned take huge hard pass expect accessories come main product good better product im buying otherwise would buy product stand alone sadly found decent pair binoculars last year much better quality phone adapter tripod defect guess im going pay ugh

Llevaré a cabo la lematización

In [17]:
import nltk

nltk.download("wordnet")
nltk.download("omw-1.4")

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

True

In [18]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

In [19]:
def lematizar_texto(texto):

    palabras = texto.split()

    palabras_lematizadas = []

    for palabra in palabras:
        palabras_lematizadas.append(lemmatizer.lemmatize(palabra))

    texto_final = " ".join(palabras_lematizadas)

    return texto_final

In [20]:
df["review_clean"] = df["review_no_stopwords"].apply(lematizar_texto)

In [21]:
print("ORIGINAL")
print(df.loc[0, "review"])

print("\nLIMPIA")
print(df.loc[0, "review_clean"])

ORIGINAL
Smells like gasoline! Going back! First & most offensive: they reek of gasoline so if you are sensitive/allergic to petroleum products like I am you will want to pass on these.  Second: the phone adapter is useless as-is. Mine was not drilled far enough to be able to tighten it into place for my iPhone 12 max. It just slipped & slid all over. Stupid me putting the adapter together first without picking up the binoculars to smell them bc I wasted 15 minutes trying to figure out how to put the adapter together bc it does not come with instructions!  I had to come back here to the website which was a total pain. Third: the tripod is also useless. I would not trust the iOS to hold my $1600 phone nor even a Mattel Barbie for that matter. It’s just inefficient for the job imo.  Third: in order to try to give an honest review I did don gloves & eyewear to check the binoculars out.  They seemed average except for mine seemed to be missing about 10% of the film costing in the lower edge of one of the lenses which would have ruined every video & photograph unplanned to take so for me these are a very huge hard pass.  I expect the accessories that come with the main product to be as good or better than the product I’m buying. Otherwise I would just buy the product as a stand alone.  Sadly, I found a decent pair of binoculars last year with a much better quality phone adapter & tripod, but they had a defect too.  Guess I’m going to have to pay more.  Ugh.

LIMPIA
smell like gasoline going back first offensive reek gasoline sensitiveallergic petroleum product like want pas second phone adapter useless asis mine drilled far enough able tighten place iphone max slipped slid stupid putting adapter together first without picking binoculars smell bc wasted minute trying figure put adapter together bc come instruction come back website total pain third tripod also useless would trust io hold phone even mattel barbie matter inefficient job imo third order try give honest review glove eyewear check binoculars seemed average except mine seemed missing film costing lower edge one lens would ruined every video photograph unplanned take huge hard pas expect accessory come main product good better product im buying otherwise would buy product stand alone sadly found decent pair binoculars last year much better quality phone adapter tripod defect guess im going pay ugh

Elimino columnas ya que ya no sirven más

In [22]:
columnas_eliminar = [
    "review_clean_basic",
    "review_no_punctuation",
    "review_no_numbers",
    "review_no_stopwords"
]

df.drop(columns=columnas_eliminar, inplace=True)

In [23]:
# Crear la variable sentiment

def clasificar_sentimiento(rating):

    if rating <= 2:
        return "Negativo"

    elif rating == 3:
        return "Neutro"

    else:
        return "Positivo"

df["sentiment"] = df["rating"].apply(clasificar_sentimiento)

In [27]:
df[["rating", "sentiment"]].head(10)

   rating sentiment
0     3.0    Neutro
1     1.0  Negativo
2     5.0  Positivo
3     5.0  Positivo
4     5.0  Positivo
5     5.0  Positivo
6     5.0  Positivo
7     5.0  Positivo
8     5.0  Positivo
9     5.0  Positivo

In [28]:
df["sentiment"].value_counts()

sentiment
Positivo    40327
Negativo     6261
Neutro       3412
Name: count, dtype: int64

In [29]:
df.columns

Index(['rating', 'title', 'text', 'images', 'asin', 'parent_asin', 'user_id',
       'timestamp', 'helpful_vote', 'verified_purchase', 'review',
       'review_length', 'review_clean', 'sentiment'],
      dtype='object')

In [30]:
#crear csv datos limpios
df.to_csv("amazon_reviews_clean.csv", index=False)

In [31]:
#descargar csv
from google.colab import files

files.download("amazon_reviews_clean.csv")